apiVersion: v1
kind: Service
metadata:
  name: apollo-mitmproxy
  namespace: apollo
spec:
  selector:
    app: apollo-mitmproxy
  ports:
  - name: wireguard-proxy
    port: 8080
    targetPort: 8080
    nodePort: 30000
    protocol: TCP
  - name: mitmproxy-web
    port: 8081
    targetPort: 8081
    nodePort: 30001
    protocol: TCP
  type: NodePort
