# REMINDER: Update the commit SHA for the docker actions periodically
# REMINDER: Update the build-args because I can't use environmental variables

name: Publish Docker image

on:
 release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      MITMPROXY_VER: 10.3.1
      MITMPROXY_WHL: mitmproxy-10.3.1-py3-none-any.whl
    steps:
      - name: Check out the repo
        uses: actions/checkout@4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@5
        with:
          images: adamhurm/apollo-mitmproxy
          tags: type=semver,pattern={{version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@3

      - name: Get mitmproxy wheel
        working-directory: ./docker/
        run: |
          curl -O https://downloads.mitmproxy.org/$MITMPROXY_VER/$MITMPROXY_WHL

      - name: Log in to Docker Hub
        uses: docker/login-action@3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@6
        with:
          build-args: |
            MITMPROXY_WHEEL=mitmproxy-10.3.1-py3-none-any.whl
          context: ./docker/
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}